name: linter
on: [push, pull_request]
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          files-changed-only: false
          # TODO: enable clang-tidy checks
          tidy-checks: -*
      - name: Linter Failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
