name: test-linux-qemu-aarch64
on: [push, pull_request]
jobs:
  # GitHub action testing of aarch64 on linux under emulation using https://github.com/uraimo/run-on-arch-action
  test-linux-qemu-aarch64:
    runs-on: ubuntu-latest
    env:
      SRC_PATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: uraimo/run-on-arch-action@v2
        name: run commands
        with:
          arch: aarch64
          distro: ubuntu_latest
          setup: |
            mkdir -p "$SRC_PATH/build"
          dockerRunArgs: |
            --volume "$SRC_PATH:/hadron"
          install: |
            export BUILD_PATH=/hadron/build
            apt-get update
            apt-get install --yes ninja-build cmake bison ragel gperf build-essential curl git
            mkdir -p $BUILD_PATH/install-ext/{lib,bin}
            cd $BUILD_PATH/install-ext/lib
            curl -O https://www.antlr.org/download/antlr-4.11.1-complete.jar
            cd $BUILD_PATH
            echo '#!/bin/bash
              java -Xmx500M -cp "${BUILD_PATH}/install-ext/lib/antlr-4.11.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool $@' > $BUILD_PATH/install-ext/bin/antlr4
            chmod u+x $BUILD_PATH/install-ext/bin/antlr4
          run: |
            export BUILD_PATH=/hadron/build
            cd $BUILD_PATH
            cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DANTLR_COMMAND_LINE=$BUILD_PATH/install-ext/bin/antlr4 ..
            cmake --build .
            ctest -C Debug -T test --output-on-failure
