name: test-macos-x86_64
on: [push, pull_request]
jobs:
  test-macos-x86_64:
    runs-on: macos-latest
    env:
      BUILD_PATH: ${{ github.workspace }}/build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          brew install cmake bison gperf ragel antlr ninja
      - name: configure
        run: |
          mkdir $BUILD_PATH && cd $BUILD_PATH
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
      - name: build
        run: |
          cd $BUILD_PATH
          cmake --build .
      - name: test
        run: |
          cd $BUILD_PATH
          ctest -C Debug -T test --output-on-failure
