name: test-windows-x86_64
on: [push, pull_request]
jobs:
  test-windows-x86_64:
    runs-on: windows-latest
    env:
      BUILD_PATH: ${{ github.workspace }}\build
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        shell: bash
        run: |
          vcpkg install --triplet x64-windows ragel gperf
          mkdir -p $BUILD_PATH/install-ext/{lib,bin}
          cd $BUILD_PATH/install-ext/lib
          curl -O https://www.antlr.org/download/antlr-4.11.1-complete.jar
          cd $BUILD_PATH
          export NEWER_JAVA=`where java | tail -n1`
          echo "\"$NEWER_JAVA\" -cp \"$BUILD_PATH\\install-ext\\lib\\antlr-4.11.1-complete.jar\" org.antlr.v4.Tool %*" > $BUILD_PATH/install-ext/bin/antlr4.bat
      - name: configure
        shell: bash
        run: |
          cd $BUILD_PATH
          cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -DANTLR_COMMAND_LINE=$BUILD_PATH/install-ext/bin/antlr4.bat -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Debug ..
      - name: build
        shell: bash
        run: |
          cd $BUILD_PATH
          cmake --build . --config=Debug
      - name: test
        shell: bash
        run: |
          cd $BUILD_PATH
          ctest -C Debug -T test --output-on-failure
